[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
metaplex_core_staking = "bQh8rUF7uq2N2KgtYhGa6Pd9Wdg2FYQBLYodqDPZ6WV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
